version: "3.8"

services:
  postgresql:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - "6433:5432"
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_DB: xsydb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: xsy
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  postgresql_data:
# docker exec -it 2964abb91a15 /bin/bash
# psql -U xsy -d xsydb -h postgresql -p 5432 -W
# CREATE EXTENSION IF NOT EXISTS vector;   --> 安装 vetor 插件
